### ISSUE TITLE
NPM is warning of a security flaw - is this package still maintained?

### ISSUE THREAD

**Issue by ZachSAEON** [Qard/onchange#105]
One of the dependencies of this package generates a warning for a 'severe' vulnerability that seems to be fixable via simply updating dependency versions.

Is this package still maintained?

**Comment by blakeembrey** [comment]
Yes, it is still maintained.

**Comment by blakeembrey** [comment]
Most likely you are commenting on https://github.com/Qard/onchange/pull/102, but since this is a patch release anyway you'd receive these changes if you did `npm install onchange` on any new project, or `npm audit fix`. It's likely due to you having the outdated sub-dependency committed in your `package-lock.json`. I can update this package, for what it's worth, but that wouldn't force you to update either (just as the sub dependency doesn't).
