### ISSUE TITLE
Unnecessary use of pipes disables terminal features

### ISSUE THREAD

**Issue by jaens** [Qard/onchange#108]
`onchange` always pipes the `stdout` of the child process, which causes the child process to think it's not running in a terminal (as that's how most utilities detect whether they are running in on).

This disables useful features such as color highlighting (in log messages etc.).

Ideally, stdout should not be piped unless it's necessary (due to the other command-line options),.

**Comment by blakeembrey** [comment]
@jaens Wouldn't you always want the output of your executed command to be printed? Changing this would be a backward incompatible change, if I understand what you're asking for. I also believe, but am not 100% familiar, that modules don't detect color based on whether they're being piped, but through `isTTY`. Can you show an example that would be fixed by avoiding piping?

**Comment by blakeembrey** [comment]
Did a test, this comes down to incorrect options for `stdio` in `spawn`. I can open a PR, it seems to work as expected in the new case.

**Comment by blakeembrey** [comment]
Released in `6.1.1`, let me know if this resolves your issue!

**Comment by jaens** [comment]
Yeah, what I meant is exactly what you did - not calling the `.pipe()` method, instead just passing through stdout directly.

Colors (isTTY) works now, thanks!
