### ISSUE TITLE
A change while executing is not picked up

### ISSUE THREAD

**Issue by raybooysen** [Qard/onchange#22]
If you use something like this:

onchange 'app/**/*.js' 'test/**/*.js' -- npm test

while npm test is executing, if there is another change to any of the watched files, npm test will not occur again.

**Comment by Qard** [comment]
That is expected behaviour. I haven't yet figured out what the best way to deal with that is.

Currently, the runner blocks new runs from starting while another is in-progress. Having parallel runs could cause unexpected behaviour. I thought about maybe using a queuing model, but that could easily grow faster than it is drained, especially with long-running actions like running a test suite.

Perhaps a single item queue would work, assuming all the changes between queue time and run time can be handled in a single run?

**Comment by raybooysen** [comment]
I think there are 2 options:

1) If a watch is detected while a run is in progress, abort and start again - I think the grunt watch task does this.
2) Or another option is to have a quiet period.  I quite like this idea, where, when a change is detected, wait for x ms for another change before kicking off the task.  This is common when you're making lots of changes to files and then want a build to run.

**Comment by limzykenneth** [comment]
I've sent a pull request that includes simply logging a message saying the new action is skipped.

I really like the idea of a queue though.

**Comment by blakeembrey** [comment]
Released with https://github.com/Qard/onchange/releases/tag/v2.1.0. The current process will be killed and spawn a new process.

**Comment by raybooysen** [comment]
Thanks!
