### ISSUE TITLE
runs but doesn't work?

### ISSUE THREAD

**Issue by theskillwithin** [Qard/onchange#38]
```
➜  hrtcup git:(new) ✗ onchange 'src/assets/css/**/*.sass' -v -- npm run build:css
onchange: watching src/assets/css/**/*.sass
```

it seems to run but when I change the file and save, nothing happens.

if I manually npm run build:css that will work.

```
➜  hrtcup git:(new) ✗ npm -v
3.10.3
➜  hrtcup git:(new) ✗ node -v
v6.5.0
```
OSX

(https://github.com/damonbauer/npm-build-boilerplate/blob/master/package.json)

**Comment by blakeembrey** [comment]
I don't see any `src/assets` folder in the project you linked to. Are you working on a branch?

**Comment by theskillwithin** [comment]
@blakeembrey 

oops here is the repo of the project I am working on, those were just the starter files I started with.

https://github.com/theskillwithin/hrtcup

**Comment by blakeembrey** [comment]
It worked for me. Can you make sure that's the command you run? Could you also make sure that you're in the right working directory when you run that? Aside from that, I don't think it's an issue with `onchange` because the change events come directly from `chokidar` - perhaps searching their issues and finding out if it's an existing issue may help.

**Comment by theskillwithin** [comment]
Oh wow I just tried running the pure command in cli again like I did originally to diagnose.  Now it works all sudden. 

onchange 'src/assets/css/**/*.sass' -v -- npm run build:css

![screen shot 2016-09-27 at 4 17 15 pm](https://cloud.githubusercontent.com/assets/8095506/18895361/ee3347fc-84cd-11e6-88cb-66ee2a73053e.png)
