### ISSUE TITLE
onchange v5 does not preserve colors

### ISSUE THREAD

**Issue by rafamel** [Qard/onchange#80]
Just upgraded to onchange@5.1.3, and looks like colors are not preserved for the command run by onchange on the stdout -it wasn't an issue on v4. It can be replicated by running, for example, eslint, with any warnings or errors.

**Comment by blakeembrey** [comment]
Can you give a replication repo? There isn’t any change between the versions that I’m aware of for this. It always just does a direct pipe of stdout. It’s possible some other TTY detection was introduced into ESLint that’s different.

**Comment by rafamel** [comment]
[This repo](https://github.com/rafamel/onchange_ex) reproduces the issue. Doing `npm i && npm start` on the `v4` folder (onchange v4) will work as desired; doing the same on the `v5` folder (onchange v5) will not.

I'm running Node v8.12.0 on a MacOS High Sierra.

**Comment by blakeembrey** [comment]
I took a quick look how a similar library does it, and it works using env flags. Would that be an adequate solution here? Ref: https://github.com/kimmobrunfeldt/concurrently/blob/313de5305f74f99c8c1215860473890ae1f1cc28/src/get-spawn-opts.js#L11

The reason it worked before and doesn't work now was because of the explicit `tty` of `process.stdout` when using the `stdio` option.

**Comment by rafamel** [comment]
Thanks for the quick resolution! Already tested the new release and it works like a charm!

**Comment by rjhilgefort** [comment]
I'm having trouble getting this to work- output remains all white. Any pointers/example on how to configure this?
